{% set name = "scalecodec" %}
{% set version = "1.2.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/polkascan/py-scale-codec/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 292a4d854aaffa25b80f932b1200eaf119253be79931e71ec7bbfdf1ed0bdffa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  script_env:
    - GITHUB_REF=refs/tags/v{{ version }}
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - base58 >=2.0.1
    - more-itertools
    - requests >=2.24.0
    - python >={{ python_min }}.*
test:
  source_files:
    - test
    - scalecodec/type_registry
  requires:
    - pip
    - pytest
    - python  {{ python_min }}
  commands:
    - pip check
    - pytest -v test

about:
  home: https://github.com/polkascan/py-scale-codec
  summary: 'Python SCALE Codec Library'
  description: |
    Substrate uses a lightweight and efficient encoding and decoding program to 
    optimize how data is sent and received over the network. The program used to 
    serialize and deserialize data is called the SCALE codec, with SCALE being an 
    acronym for Simple Concatenated Aggregate Little-Endian.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - arjanz
    - MementoRC
